### ISSUE TITLE
Pre-trained model for the multi-frame prediction mode

### ISSUE THREAD

**Issue by fabiencastan** [Riccorl/Super-SloMo-tf2#2]
Hi,
There is a pre-trained model for using the single frame prediction mode. Is there a pre-trained model available for the multi-frame prediction mode in order to reproduce the results of the paper?
Best Regards,
Fabien

**Comment by Riccorl** [comment]
Unfortunately there isn't. We don't have enough gpu power to train that model. If I remember correctly, it takes more than 45 minutes per epoch on Colab with 5 intermediate frames.
